{% set name = "poppler-data" %}
{% set version = "0.4.10" %}
{% set sha256 = "6e2fcef66ec8c44625f94292ccf8af9f1d918b410d5aa69c274ce67387967b30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script:
    - make install prefix=$PREFIX

requirements:
  build:
    - make

test:
  commands:
    - test -f $PREFIX/share/poppler/cidToUnicode/Adobe-CNS1

about:
  home: https://poppler.freedesktop.org/
  license: Adobe+GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'Encoding data for the Poppler PDF manipulation library.'

extra:
  recipe-maintainers:
    - pkgw
