{% set name = "poppler-data" %}
{% set version = "0.4.11" %}
{% set sha256 = "2cec05cd1bb03af98a8b06a1e22f6e6e1a65b1e2f3816cb3069bb0874825f08c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://poppler.freedesktop.org/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script:
    - make install prefix=$PREFIX

requirements:
  build:
    - make

test:
  commands:
    - test -f $PREFIX/share/poppler/cidToUnicode/Adobe-CNS1

about:
  home: https://poppler.freedesktop.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Encoding data for the Poppler PDF manipulation library.'
  dev_url: https://gitlab.freedesktop.org/poppler/poppler-data
  doc_url: https://freedesktop.org/wiki/Software/poppler/

extra:
  recipe-maintainers:
    - pkgw
