travis:
  secure:
    BINSTAR_TOKEN: RwTcHqNjaCe0YyELYGf3nkI9fGdgXPqpwQMkVsiWEDHCY5Otr3WgwaVwItl2xIGECBg0WOwxnR/8YQFQs9EEjXLyaet4sDNFsZ2eygOD6b+rBIzaS/Qk4DTx14q38QwWrRPlhOH6d01oeQ6icAbL1ENeLVT+NemMGGKwElMvhROK+jlA7WsP9VHBsn/mtBwGRCkeKdDtZtZNWOj/cRDcJYsNzAP6JoD01+l1JL0KNSIA5OWsxOl4ycEnJlHCcQDa/QBflJoe1iSXza2GYs7pbyohZXEzJhAfDxeep0O+EQfuQFmy1iakxJeqqudZabzo2D1YnFkBO+L0DqVoK6v32bjgOiE13vOuIXayEPBH0/CMEEMzZp3OFK4DOstNl2UtWxxQ3FchRoQQa43ezaepOWoPwm9NInJcCiMz6amdff3iuBgYLHz+UVSCDebYEw4ZAg6zsKaaDbTNR1wmulkF+zRuthrk/cjg5reNpYusuXjyAwCjKzhAaoFU1Uh5nffOtWwDrXSutXl0LlzGmjaSvZlFB/X6+TbjUJj60R1VKxiwOb1HrMliu+4sTp/O4iG1/B6q5G7oI98NBChIbSYfGVyOwT/v5XjoXetu1LOvNuJuxZJ/Bv/IUzrx9MTc1VkdDvGwONs36uiOK7EXcOtMZlQXAss2BbMx/0F4e8hbczY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
