travis:
  secure:
    BINSTAR_TOKEN: 1yDC4cBl/cFpFXdTJRLH4c+99Ir5H4M+hAqftE0sxWpgfoefpScuXYQTBPxtuFpzSF+HZhAZf+0uERmi+LU2yAbtRbMKA9krBpwCSBpo9If6Ogc0FiLWMqQ4lFvEYthhYtF87E/ZLCgJgx+B9vfP/i89MynVI7krXI1PP1TiFP79HJygfrLY234EEO4AC3MX6Aw2NXiX7Z0rQEo6/xgSZCoW7+LSMAP0DYwzHeh8RYfWyCFzBxAj1NZPUQIBaozAXI7StcabHI/8ZdUQe1Itvm9N26H353DKbLo7jjfRi6lyaA2Xg9HnoldsTAXJv0T/xsYc5SX6kAvjy3zmd26kIS7bduijWHKJEtblZSar0/dFgJyMK0JdDbwNdL+8RaNtAy9Dk7Nxho3oM9fRRr9wxC+ViEMebTOOsf6iJ85HnLW8jcQimCzl8vJpUpYNGfZ4JhDab5XjpG4hjrlMaKxPqFCSmehrv1hMmYdsMZnEZK1N90CMlY1MJJDlZVvGVOmYtwdn8PfLEmK4aThKMKc6aDgL4ODddYQ3amwRuN1v30V2RrnWqKPGoE1s0o0XjuFt9gHcgLoZMM2UnM2mRNMSWdxNwbI/b+HP9o4WRzu3/trhLBYFRsMi+57CXf/B0XiLyNqa9ken+Rh5+NLYPMVGs3COGNmW3DQ2hqehIAAZ6os=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
