travis:
  secure:
    BINSTAR_TOKEN: HRBAX5FVILnmPjQYYgvmNWmjxD6iUyba0Vq4iat6DnYobRQMLY5hoYfT/NlWSKQGzKl0wnRy1NMOGHongbqhrD6LA6fjvPq9N+PRim1Tt48uAr6DSTSeeaylXzT+Ht959SniQ3hMQeiEjxI7xPEGFAd/BkBULq8r2fqbD8JEU8JjBbYENjE0qHX6wXZv0KLm7cibFtuH2ezaKaFvfDCkMYzpkFSU0fKHmK4OqZKfIUByD2nP4SrqYt9A6+ReZmqAchDJvmRH9AJljKClQhZTFxfqFG9NZi8rR3NMnB4YHTSEPj7hWkCrHPLeLUkpuI33jRL8AHnbiwqfSPQh5hUFvZsqRDiWwXgLAHfQasrRgQSIvKaTkB2PLhQkdql75inLr2K9QEKhmxlJj4dTOyGGfmLRlaU/15/u3bXTB98xocqyDwoAxcEP9Pzbwf5llwraauzncqQoHT2rD1/MGIVH3eXLkjFfKEsrjitT+xhBlIiyMqBSnHkCnB4LBFTKPQ+rz+7+Uc5WQbiNG5MY4TATPohUZeQxTnlAiLqdi7PLZCS/ME1DgmEmBTsITfqaLOsQmnrDAsi0qWA9K5a1anVG0sSRXMNzdV9ZyksuzloLNQRa1+j0x4L3wl/u/NCUijWVInkLBdjslC5QAeV6TfivCCX6sjZ0MWzQ3nHWIzp+V+0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
